# Generated by Django 5.2.14 on 2026-05-18 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('learning', 'Learning'), ('reading', 'Reading'), ('movement', 'Movement'), ('creative', 'Creative'), ('reflection', 'Reflection'), ('entertainment', 'Entertainment'), ('documentary', 'Documentary'), ('customization', 'Customization'), ('blocked', 'Blocked')], max_length=20)),
                ('duration_minutes', models.PositiveSmallIntegerField(default=0)),
                ('points_spent', models.PositiveSmallIntegerField(default=0)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_sessions', to='profiles.childprofile')),
                ('content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_sessions', to='learning.contentitem')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
