# Generated by Django 5.2.14 on 2026-05-19 04:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_logger', '0002_activity_alerts_entertainment'),
        ('profiles', '0003_childprofile_favorite_subjects'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentOverrideLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('pin_change', 'PIN changed'), ('pin_reset', 'PIN reset'), ('rule_change', 'Rule changed'), ('content_approve', 'Content approved'), ('content_block', 'Content blocked'), ('child_data_export', 'Child data exported'), ('child_data_delete', 'Child data deleted'), ('entertainment_pause', 'Entertainment paused'), ('entertainment_resume', 'Entertainment resumed'), ('manual_point_adjust', 'Manual point adjustment')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='override_logs', to='profiles.childprofile')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='override_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
