# Generated by Django 5.2.14 on 2026-05-20 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_logger', '0004_usage_screen_time_choice'),
        ('profiles', '0004_parentrule_continuous_screen_time_limit_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usagesession',
            name='abandoned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usagesession',
            name='activity_category',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='usagesession',
            name='display_category',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='usagesession',
            name='last_heartbeat_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usagesession',
            name='screen_based',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usagesession',
            name='screen_class',
            field=models.CharField(blank=True, choices=[('screen_learning', 'Screen learning'), ('screen_discovery', 'Screen discovery'), ('screen_healthy_entertainment', 'Screen healthy entertainment'), ('screen_mascot', 'Screen mascot'), ('offscreen_task', 'Off-screen task'), ('offscreen_break', 'Off-screen break'), ('idle_screen', 'Idle screen')], max_length=32),
        ),
        migrations.AddField(
            model_name='usagesession',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('paused', 'Paused'), ('blocked', 'Blocked'), ('abandoned', 'Abandoned')], default='completed', max_length=16),
        ),
        migrations.AddField(
            model_name='usagesession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='ChildModeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('paused', 'Paused'), ('abandoned', 'Abandoned')], default='active', max_length=16)),
                ('ended_reason', models.CharField(blank=True, choices=[('manual_end', 'Manual end'), ('session_limit', 'Session limit'), ('parent_end', 'Parent end'), ('abandoned', 'Abandoned')], max_length=20)),
                ('session_minutes', models.PositiveIntegerField(default=0)),
                ('screen_minutes', models.PositiveIntegerField(default=0)),
                ('continuous_screen_minutes', models.PositiveIntegerField(default=0)),
                ('offscreen_minutes', models.PositiveIntegerField(default=0)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('current_activity_type', models.CharField(blank=True, max_length=40)),
                ('current_activity_title', models.CharField(blank=True, max_length=160)),
                ('current_segment_started_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_mode_sessions', to='profiles.childprofile')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='BreakRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggered_by', models.CharField(choices=[('continuous_limit', 'Continuous limit')], max_length=24)),
                ('required_minutes', models.PositiveSmallIntegerField(default=5)),
                ('started_at', models.DateTimeField()),
                ('timer_completed_at', models.DateTimeField(blank=True, null=True)),
                ('task_completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled_by_parent', 'Cancelled by parent'), ('expired', 'Expired')], default='pending', max_length=24)),
                ('reason_code', models.CharField(blank=True, max_length=40)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offscreen_task_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_breaks', to='activity_logger.usagesession')),
                ('child_mode_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='break_requirements', to='activity_logger.childmodesession')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='usagesession',
            name='child_mode_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='activity_logger.childmodesession'),
        ),
    ]
