[project]
name = "kindy-mate-ai"
version = "0.1.0"
description = "AI Tracker for KINDY-MATE"
requires-python = ">=3.10,<3.11"
dependencies = [
    "fastapi",
    "uvicorn",
    "websockets",
    "mediapipe==0.10.11",
    "opencv-python-headless",
    "numpy",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
