# Generated by Django 5.2.14 on 2026-05-18 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=80)),
                ('age', models.PositiveSmallIntegerField()),
                ('avatar_id', models.CharField(default='milo', max_length=40)),
                ('interests', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nickname'],
            },
        ),
        migrations.CreateModel(
            name='ParentRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_entertainment_cap_minutes', models.PositiveSmallIntegerField(default=20)),
                ('bedtime_lock_start', models.TimeField(blank=True, null=True)),
                ('bedtime_lock_end', models.TimeField(blank=True, null=True)),
                ('point_conversion_rate', models.PositiveSmallIntegerField(default=2)),
                ('cooldown_minutes', models.PositiveSmallIntegerField(default=15)),
                ('voice_enabled', models.BooleanField(default=False)),
                ('camera_enabled', models.BooleanField(default=False)),
                ('entertainment_paused', models.BooleanField(default=False)),
                ('allowed_categories', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='profiles.childprofile')),
            ],
        ),
    ]
