# Generated by Django 5.2.14 on 2026-05-18 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_professional_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='childprofile',
            name='favorite_subjects',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
