# Generated by Django 5.2.14 on 2026-05-20 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_childprofile_favorite_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentrule',
            name='continuous_screen_time_limit_minutes',
            field=models.PositiveSmallIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='parentrule',
            name='minimum_offscreen_break_minutes',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='parentrule',
            name='session_duration_limit_minutes',
            field=models.PositiveSmallIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='parentrule',
            name='time_profile',
            field=models.CharField(choices=[('low_screen', 'Low screen'), ('balanced', 'Balanced'), ('learning_focused', 'Learning focused'), ('custom', 'Custom')], default='balanced', max_length=24),
        ),
        migrations.AddField(
            model_name='parentrule',
            name='total_screen_time_limit_minutes',
            field=models.PositiveSmallIntegerField(default=35),
        ),
    ]
