# Generated by Django 5.2.14 on 2026-05-18 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('content_type', models.CharField(choices=[('learning', 'Learning'), ('reading', 'Reading'), ('movement', 'Movement'), ('creative', 'Creative'), ('reflection', 'Reflection'), ('entertainment', 'Entertainment'), ('documentary', 'Documentary'), ('customization', 'Customization')], max_length=24)),
                ('age_min', models.PositiveSmallIntegerField(default=5)),
                ('age_max', models.PositiveSmallIntegerField(default=9)),
                ('difficulty_level', models.CharField(default='easy', max_length=40)),
                ('estimated_duration_minutes', models.PositiveSmallIntegerField(default=5)),
                ('stimulation_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=12)),
                ('requires_audio', models.BooleanField(default=False)),
                ('requires_camera', models.BooleanField(default=False)),
                ('requires_parent_approval', models.BooleanField(default=False)),
                ('approval_status', models.CharField(choices=[('approved', 'Approved'), ('needs_review', 'Needs review'), ('blocked', 'Blocked')], default='approved', max_length=16)),
                ('source_name', models.CharField(default='Kindy-Mate demo content', max_length=120)),
                ('source_url_or_reference', models.CharField(blank=True, max_length=255)),
                ('license_status', models.CharField(default='Internal demo only', max_length=120)),
                ('learning_objective', models.TextField()),
                ('related_sdg', models.CharField(blank=True, max_length=20)),
                ('points_reward_or_cost', models.IntegerField(default=0)),
                ('cooldown_category', models.CharField(blank=True, max_length=60)),
                ('safety_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['content_type', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_type', models.CharField(choices=[('learning', 'Learning'), ('reading', 'Reading'), ('movement', 'Movement'), ('creative', 'Creative'), ('reflection', 'Reflection')], max_length=16)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField()),
                ('age_min', models.PositiveSmallIntegerField(default=5)),
                ('age_max', models.PositiveSmallIntegerField(default=9)),
                ('difficulty', models.CharField(default='easy', max_length=40)),
                ('estimated_duration_minutes', models.PositiveSmallIntegerField(default=5)),
                ('points_reward', models.PositiveSmallIntegerField(default=5)),
                ('requires_voice', models.BooleanField(default=False)),
                ('requires_camera', models.BooleanField(default=False)),
                ('verification_method', models.CharField(default='rule_based', max_length=120)),
                ('safety_notes', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions', to='learning.contentitem')),
            ],
            options={
                'ordering': ['mission_type', 'title'],
            },
        ),
        migrations.CreateModel(
            name='MissionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('blocked', 'Blocked')], default='started', max_length=16)),
                ('score', models.PositiveSmallIntegerField(default=100)),
                ('points_awarded', models.PositiveSmallIntegerField(default=0)),
                ('verification_method', models.CharField(default='rule_based', max_length=120)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mission_attempts', to='profiles.childprofile')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='learning.mission')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
