# Generated by Django 5.2.14 on 2026-05-19 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_content_mission_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentitem',
            name='display_category',
            field=models.CharField(choices=[('hoc_hanh', 'Học hành'), ('doc_sach', 'Đọc sách'), ('van_dong', 'Vận động'), ('ky_nang_song', 'Kỹ năng sống'), ('sang_tao', 'Sáng tạo'), ('phim_hoat_hinh', 'Phim hoạt hình'), ('kham_pha_khoa_hoc', 'Khám phá khoa học'), ('to_mau', 'Tô màu'), ('game_nhe_nhang', 'Game nhẹ nhàng'), ('mascot', 'Đồ cho mascot')], default='hoc_hanh', max_length=32),
        ),
        migrations.AddField(
            model_name='mission',
            name='display_category',
            field=models.CharField(choices=[('hoc_hanh', 'Học hành'), ('doc_sach', 'Đọc sách'), ('van_dong', 'Vận động'), ('ky_nang_song', 'Kỹ năng sống'), ('sang_tao', 'Sáng tạo')], default='hoc_hanh', max_length=24),
        ),
    ]
