# Generated by Django 5.2.14 on 2026-05-21 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_contentitem_display_category_and_more'),
        ('profiles', '0004_parentrule_continuous_screen_time_limit_minutes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('title', models.CharField(max_length=255)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_videos', to='profiles.childprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
