# Generated by Django 5.2.14 on 2026-05-27 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_assignedvideo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssignedVideo',
        ),
    ]
