# Generated by Django 5.2.14 on 2026-05-19 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_rewarditem_mascot'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewarditem',
            name='display_category',
            field=models.CharField(choices=[('phim_hoat_hinh', 'Phim hoạt hình'), ('kham_pha_khoa_hoc', 'Khám phá khoa học'), ('to_mau', 'Tô màu'), ('game_nhe_nhang', 'Game nhẹ nhàng'), ('mascot', 'Đồ cho mascot')], default='game_nhe_nhang', max_length=32),
        ),
    ]
